### ISSUE TITLE
Potential bug in conjugate_gradient and general_conjugate_gradient

### ISSUE THREAD

**Issue by ran-weii** [devzhk/cgds-package#2]
Hello, 

I was using ACGD for a constrained optimization problem with the Lagrange multiplier method. I let the primal parameters be the min player and the Lagrange multiplier be the max player. 

With the Lagrange multiplier having a dimension of 1, after the first iteration my ```nsteps``` equals 0 after after line 168. This creates an error in line 200 ```if i > 100:```. 

I currently solved it by inserting in line 178: ```i = 0```. The results I got make sense. 

Without going too much into the theory while using this, I was wondering if ACGD is the correct choice and if my fix makes sense.

Thank you!

**Comment by devzhk** [comment]
Yes! ACGD is the right choice for Lagrange Multipliers for constrained optimization problem. 

Thanks for pointing out this corner case. I just fix it in the latest version. Please let me know if it solves the problem. 

Best

**Comment by ran-weii** [comment]
Hi thank you it worked for ACGD. I believe you did not change conjugate_gradient so CGD might run into the same problem.
